import { create } from 'zustand';
import { persist, createJSONStorage } from 'zustand/middleware';
import { immer } from 'zustand/middleware/immer';
import { dexieStorage } from '../db';
import { current } from 'immer';
import type {
  Student,
  Seat,
  OptimizationResult,
  ObjectiveWeights,
  GeneticConfig,
  SeatingConstraints,
  ClassProject,
  RotationPlan,
  SavedArrangement,
} from '../../types';
import type { LayoutDef } from '../layouts';

export type HeatMapMode = 'none' | 'academic' | 'behavior' | 'gender' | 'conflicts';
export type ViewMode = 'rows' | 'pairs' | 'clusters';

interface AppState {
  // Students
  students: Student[];
  addStudent: (student: Student) => void;
  updateStudent: (id: string, student: Partial<Student>) => void;
  removeStudent: (id: string) => void;
  setStudents: (students: Student[]) => void;

  // Layout config
  rows: number;
  cols: number;
  setRows: (rows: number) => void;
  setCols: (cols: number) => void;

  /**
   * Layout definition (shape of the classroom). Drives both the optimizer
   * and the renderer. Defaults to `{ type: 'rows', rows, cols }` so
   * existing projects keep working.
   */
  layoutDef: LayoutDef;
  setLayoutDef: (def: LayoutDef) => void;

  // Optimization
  isOptimizing: boolean;
  result: OptimizationResult | null;
  /** Student positions from the previous optimization run, captured the
   *  moment a NEW result arrives. Used for the "show what moved"
   *  highlight. Cleared when result itself is cleared. */
  previousPositions: Record<string, { row: number; col: number }> | null;

  /** Rolling history of optimization runs. Capped at 20 entries so
   *  storage stays small. Used to surface "who has this student sat
   *  with recently?" insights in the detail drawer. */
  resultHistory: Array<{
    timestamp: string;
    positions: Record<string, { row: number; col: number }>;
  }>;
  showMovementDiff: boolean;
  setOptimizing: (value: boolean) => void;
  setResult: (result: OptimizationResult | null) => void;
  setShowMovementDiff: (v: boolean) => void;

  // Weights
  weights: ObjectiveWeights;
  setWeights: (weights: ObjectiveWeights) => void;

  // Config
  config: GeneticConfig;
  setConfig: (config: GeneticConfig) => void;

  // Constraints
  constraints: SeatingConstraints;
  setConstraints: (constraints: SeatingConstraints) => void;

  /** "Freshen seating": when on, the optimizer penalizes re-seating
   *  students next to neighbors they recently sat with, so repeated runs
   *  rotate the room. Opt-in; only has an effect once a run history exists. */
  avoidRecentNeighbors: boolean;
  setAvoidRecentNeighbors: (v: boolean) => void;

  /** Saved term rotation plan — an ordered list of seating periods that
   *  rotate students around the room across a term. Generated by the
   *  rotation planner; persisted so it survives reloads. */
  rotationPlan: RotationPlan | null;
  /** Which period of the plan is currently shown on the grid, or null. */
  activeRotationPeriodId: string | null;
  /** Store a freshly generated plan (or null to clear it). Passing a plan
   *  immediately shows its first period on the grid. */
  setRotationPlan: (plan: RotationPlan | null) => void;
  /** Show a specific period's seating on the grid without touching the
   *  rolling run history. */
  viewRotationPeriod: (periodId: string) => void;

  /** Named seating arrangements saved within the current class. Lets the
   *  teacher keep several alternatives ("Plan A", "Exam layout") and switch
   *  between them. Persisted and carried in project snapshots. */
  savedArrangements: SavedArrangement[];
  /** Which saved arrangement is currently shown on the grid, or null. */
  activeArrangementId: string | null;
  /** Save the current `result` under a name. No-op when there's no result. */
  saveArrangement: (name: string) => void;
  /** Show a saved arrangement on the grid (without touching run history). */
  loadArrangement: (id: string) => void;
  deleteArrangement: (id: string) => void;
  renameArrangement: (id: string, name: string) => void;

  /** Step-1 questionnaire progress. `consentAck` records that the teacher
   *  has confirmed they have permission to collect this data; `surveyedIds`
   *  tracks which students have been through the survey; `skipPeers` is the
   *  cold-start toggle (class doesn't know each other yet). */
  questionnaire: { consentAck: boolean; surveyedIds: string[]; skipPeers: boolean };
  /** Transient: whether the guided questionnaire modal is open. */
  questionnaireOpen: boolean;
  setQuestionnaireOpen: (v: boolean) => void;
  setQuestionnaireConsent: (v: boolean) => void;
  setQuestionnaireSkipPeers: (v: boolean) => void;
  markStudentSurveyed: (id: string) => void;
  resetQuestionnaire: () => void;

  // UI State
  selectedStudentId: string | null;
  setSelectedStudentId: (id: string | null) => void;
  sidebarOpen: boolean;
  setSidebarOpen: (open: boolean) => void;

  // --- Seating Map UI ---
  lockedSeats: string[];            // seat keys "row-col"
  heatMapMode: HeatMapMode;
  zoomLevel: number;
  viewMode: ViewMode;
  selectedSeatKey: string | null;   // for click-to-swap
  showRelations: boolean;
  showTimeline: boolean;             // show optimization timeline panel

  /** Student whose detail drawer is currently open, or null. */
  detailsTargetStudentId: string | null;
  setDetailsTarget: (id: string | null) => void;

  toggleLockSeat: (seatKey: string) => void;
  setHeatMapMode: (mode: HeatMapMode) => void;
  setZoomLevel: (level: number) => void;
  setViewMode: (mode: ViewMode) => void;
  setSelectedSeat: (key: string | null) => void;
  setShowRelations: (show: boolean) => void;
  setShowTimeline: (show: boolean) => void;

  // Swap two seats (pushes to undo history)
  swapStudents: (seatKeyA: string, seatKeyB: string) => void;

  // Undo / Redo
  history: OptimizationResult[];
  historyFuture: OptimizationResult[];
  undo: () => void;
  redo: () => void;

  // UI Language
  uiLanguage: 'en' | 'he' | 'ar' | 'ru';
  setUiLanguage: (lang: 'en' | 'he' | 'ar' | 'ru') => void;

  // UI scale ("sm" | "md" | "lg") — lets teachers bump text size up for
  // readability without changing browser zoom.
  uiScale: 'sm' | 'md' | 'lg';
  setUiScale: (scale: 'sm' | 'md' | 'lg') => void;

  /** Color theme. 'system' follows the OS preference. */
  theme: 'light' | 'dark' | 'system';
  setTheme: (theme: 'light' | 'dark' | 'system') => void;

  /** Whether the welcome-tips modal has been dismissed.
   *  Persisted so it never auto-pops twice for the same teacher. */
  welcomeTipsDismissed: boolean;
  setWelcomeTipsDismissed: (v: boolean) => void;

  /** Optional client-side LLM integration. Off by default. The API
   *  key is stored only in this browser's IndexedDB — no server, no
   *  telemetry. */
  aiSettings: {
    enabled: boolean;
    apiKey: string;
    model: string;
  };
  setAiSettings: (s: { enabled: boolean; apiKey: string; model: string }) => void;
  forgetApiKey: () => void;

  // Whether the results stack (metrics + explanation) starts collapsed so
  // the seating map dominates the viewport.
  resultsCollapsed: boolean;
  setResultsCollapsed: (v: boolean) => void;

  // Projects
  projects: ClassProject[];
  currentProjectId: string | null;
  saveProject: (name: string) => void;
  loadProject: (id: string) => void;
  deleteProject: (id: string) => void;
  renameProject: (id: string, name: string) => void;

  /** Replace the entire persistable state from a validated backup. The
   *  current AI API key is preserved (backups never carry the key) and
   *  any transient UI is reset so the new data renders cleanly. */
  restoreFromBackup: (data: import('../../features/projects/backup').BackupData) => void;
}

const defaultWeights: ObjectiveWeights = {
  academic_balance: 0.3,
  behavioral_balance: 0.3,
  diversity: 0.2,
  special_needs: 0.2,
};

const defaultConfig: GeneticConfig = {
  populationSize: 100,
  maxGenerations: 100,
  crossoverRate: 0.8,
  mutationRate: 0.2,
  tournamentSize: 3,
  earlyStopPatience: 20,
  // 3 independent starts strikes a good balance: noticeably better
  // results than 1 (especially on conflict-heavy classes), still
  // sub-second for typical 30-student rosters.
  multiStart: 3,
};

const defaultConstraints: SeatingConstraints = {
  separate_pairs: [],
  keep_together_pairs: [],
  front_row_ids: [],
  back_row_ids: [],
};

export const useStore = create<AppState>()(
  persist(
    immer((set) => ({
      // Students
      students: [],
      addStudent: (student) =>
        set((state) => {
          state.students.push(student);
          state.rotationPlan = null;
          state.activeRotationPeriodId = null;
          state.savedArrangements = [];
          state.activeArrangementId = null;
        }),
      updateStudent: (id, updates) =>
        set((state) => {
          const index = state.students.findIndex((s: Student) => s.id === id);
          if (index !== -1) {
            state.students[index] = { ...state.students[index], ...updates };
          }
        }),
      removeStudent: (id) =>
        set((state) => {
          state.students = state.students.filter((s: Student) => s.id !== id);
          state.rotationPlan = null;
          state.activeRotationPeriodId = null;
          state.savedArrangements = [];
          state.activeArrangementId = null;
        }),
      setStudents: (students) =>
        set((state) => {
          state.students = students;
          state.rotationPlan = null;
          state.activeRotationPeriodId = null;
          state.savedArrangements = [];
          state.activeArrangementId = null;
        }),

      // Layout
      rows: 4,
      cols: 5,
      setRows: (rows) => {
        // Route through setLayoutDef so the result-invalidation logic runs.
        const { layoutDef, setLayoutDef } = useStore.getState();
        setLayoutDef({ ...layoutDef, rows });
      },
      setCols: (cols) => {
        const { layoutDef, setLayoutDef } = useStore.getState();
        setLayoutDef({ ...layoutDef, cols });
      },

      layoutDef: { type: 'rows', rows: 4, cols: 5 },
      setLayoutDef: (def) =>
        set((state) => {
          // Clear any stale optimization result when the shape of the room
          // changes — the old seat positions no longer match the new
          // layout, so showing them in the new renderer would look broken.
          // Changes that only adjust rows/cols within the same layout type
          // also invalidate the result because the seat count differs.
          const prev = state.layoutDef;
          const shapeChanged =
            prev.type !== def.type ||
            prev.rows !== def.rows ||
            prev.cols !== def.cols ||
            prev.clusterSize !== def.clusterSize ||
            JSON.stringify(prev.customRowSizes ?? []) !==
              JSON.stringify(def.customRowSizes ?? []) ||
            JSON.stringify(prev.blockedCells ?? []) !==
              JSON.stringify(def.blockedCells ?? []);
          state.layoutDef = def;
          state.rows = def.rows;
          state.cols = def.cols;
          if (shapeChanged) {
            state.result = null;
            state.lockedSeats = [];
            state.selectedSeatKey = null;
            // A saved rotation plan's seat coordinates no longer map onto
            // the new room shape, so drop it too.
            state.rotationPlan = null;
            state.activeRotationPeriodId = null;
            // Likewise saved arrangements snapshot specific seat positions.
            state.savedArrangements = [];
            state.activeArrangementId = null;
          }
        }),

      // Optimization
      isOptimizing: false,
      result: null,
      previousPositions: null,
      resultHistory: [],
      showMovementDiff: false,
      setOptimizing: (value) =>
        set((state) => {
          state.isOptimizing = value;
        }),
      setResult: (result) =>
        set((state) => {
          // Capture the previous run's positions so the UI can highlight
          // who moved between optimizations. Only swap in when a NEW result
          // arrives (not when clearing) so a layout-change wipe doesn't
          // drop the prior baseline.
          if (result && state.result) {
            state.previousPositions = state.result.student_positions;
          } else if (!result) {
            state.previousPositions = null;
          }
          state.result = result;

          // Append to rolling result history (capped at 20 entries) so
          // the rotation tracker can answer "who has this student sat
          // with recently?". Skip the append when clearing (result is
          // null) — that's a state reset, not a new run.
          if (result) {
            const positions: Record<string, { row: number; col: number }> = {};
            for (const [id, p] of Object.entries(result.student_positions)) {
              positions[id] = { row: p.row, col: p.col };
            }
            state.resultHistory = [
              { timestamp: new Date().toISOString(), positions },
              ...state.resultHistory,
            ].slice(0, 20);
          }

          // New optimization clears undo history
          state.history = [];
          state.historyFuture = [];
        }),

      // Weights
      weights: defaultWeights,
      setWeights: (weights) =>
        set((state) => {
          state.weights = weights;
        }),

      // Config
      config: defaultConfig,
      setConfig: (config) =>
        set((state) => {
          state.config = config;
        }),

      // Constraints
      constraints: defaultConstraints,
      setConstraints: (constraints) =>
        set((state) => {
          state.constraints = constraints;
        }),

      avoidRecentNeighbors: false,
      setAvoidRecentNeighbors: (v) =>
        set((state) => {
          state.avoidRecentNeighbors = v;
        }),

      rotationPlan: null,
      activeRotationPeriodId: null,
      setRotationPlan: (plan) =>
        set((state) => {
          state.rotationPlan = plan;
          if (plan && plan.periods.length > 0) {
            const first = plan.periods[0];
            state.activeRotationPeriodId = first.id;
            // Show the first period on the grid. Set result directly (not
            // via setResult) so generating a plan doesn't flood the rolling
            // run history with every period.
            state.result = first.result;
            state.previousPositions = null;
            state.history = [];
            state.historyFuture = [];
          } else {
            state.activeRotationPeriodId = null;
          }
        }),
      questionnaire: { consentAck: false, surveyedIds: [], skipPeers: false },
      questionnaireOpen: false,
      setQuestionnaireOpen: (v) =>
        set((state) => {
          state.questionnaireOpen = v;
        }),
      setQuestionnaireConsent: (v) =>
        set((state) => {
          state.questionnaire.consentAck = v;
        }),
      setQuestionnaireSkipPeers: (v) =>
        set((state) => {
          state.questionnaire.skipPeers = v;
        }),
      markStudentSurveyed: (id) =>
        set((state) => {
          if (!state.questionnaire.surveyedIds.includes(id)) {
            state.questionnaire.surveyedIds.push(id);
          }
        }),
      resetQuestionnaire: () =>
        set((state) => {
          state.questionnaire.surveyedIds = [];
        }),

      viewRotationPeriod: (periodId) =>
        set((state) => {
          const plan = state.rotationPlan;
          if (!plan) return;
          const period = plan.periods.find((p) => p.id === periodId);
          if (!period) return;
          // Capture the currently shown positions so the "what moved"
          // highlight reveals how seating shifts week-to-week.
          if (state.result) {
            state.previousPositions = state.result.student_positions;
          }
          state.activeRotationPeriodId = periodId;
          state.result = period.result;
          state.history = [];
          state.historyFuture = [];
        }),

      savedArrangements: [],
      activeArrangementId: null,
      saveArrangement: (name) =>
        set((state) => {
          if (!state.result) return;
          const id = `arr_${Date.now()}`;
          state.savedArrangements.push({
            id,
            name,
            createdAt: new Date().toISOString(),
            result: structuredClone(current(state.result)) as OptimizationResult,
          });
          state.activeArrangementId = id;
        }),
      loadArrangement: (id) =>
        set((state) => {
          const arr = state.savedArrangements.find((a) => a.id === id);
          if (!arr) return;
          // Capture current positions so the "what moved" highlight shows the
          // shift to the loaded arrangement.
          if (state.result) {
            state.previousPositions = state.result.student_positions;
          }
          state.activeArrangementId = id;
          state.result = structuredClone(arr.result) as OptimizationResult;
          state.history = [];
          state.historyFuture = [];
        }),
      deleteArrangement: (id) =>
        set((state) => {
          state.savedArrangements = state.savedArrangements.filter((a) => a.id !== id);
          if (state.activeArrangementId === id) state.activeArrangementId = null;
        }),
      renameArrangement: (id, name) =>
        set((state) => {
          const arr = state.savedArrangements.find((a) => a.id === id);
          if (arr) arr.name = name;
        }),

      // UI
      selectedStudentId: null,
      setSelectedStudentId: (id) =>
        set((state) => {
          state.selectedStudentId = id;
        }),
      sidebarOpen: true,
      setSidebarOpen: (open) =>
        set((state) => {
          state.sidebarOpen = open;
        }),

      // --- Seating Map UI ---
      lockedSeats: [],
      heatMapMode: 'none',
      zoomLevel: 1.0,
      viewMode: 'rows',
      selectedSeatKey: null,

      detailsTargetStudentId: null,
      setDetailsTarget: (id) =>
        set((state) => { state.detailsTargetStudentId = id; }),

      showRelations: false,
      showTimeline: false,

      toggleLockSeat: (seatKey) =>
        set((state) => {
          const idx = state.lockedSeats.indexOf(seatKey);
          if (idx === -1) {
            state.lockedSeats.push(seatKey);
          } else {
            state.lockedSeats.splice(idx, 1);
          }
        }),
      setHeatMapMode: (mode) =>
        set((state) => {
          state.heatMapMode = mode;
        }),
      setZoomLevel: (level) =>
        set((state) => {
          state.zoomLevel = Math.min(1.5, Math.max(0.6, level));
        }),
      setViewMode: (mode) =>
        set((state) => {
          state.viewMode = mode;
        }),
      setSelectedSeat: (key) =>
        set((state) => {
          state.selectedSeatKey = key;
        }),
      setShowRelations: (show) =>
        set((state) => {
          state.showRelations = show;
        }),
      setShowTimeline: (show) =>
        set((state) => {
          state.showTimeline = show;
        }),

      // Swap two students and push to undo history
      swapStudents: (seatKeyA, seatKeyB) =>
        set((state) => {
          if (!state.result || seatKeyA === seatKeyB) return;

          // Snapshot current result for undo
          const snapshot = structuredClone(current(state.result)) as OptimizationResult;
          state.history = [...state.history, snapshot].slice(-20);
          state.historyFuture = [];

          // Parse seat keys
          const [rowA, colA] = seatKeyA.split('-').map(Number);
          const [rowB, colB] = seatKeyB.split('-').map(Number);

          const seats = state.result.layout.seats;
          const seatA = seats.find(
            (s: Seat) => s.position.row === rowA && s.position.col === colA
          );
          const seatB = seats.find(
            (s: Seat) => s.position.row === rowB && s.position.col === colB
          );
          if (!seatA || !seatB) return;

          const studentIdA = seatA.student_id;
          const studentIdB = seatB.student_id;

          // Swap student IDs
          seatA.student_id = studentIdB;
          seatA.is_empty = studentIdB === undefined;
          seatB.student_id = studentIdA;
          seatB.is_empty = studentIdA === undefined;

          // Update student_positions map
          if (studentIdA !== undefined) {
            state.result.student_positions[studentIdA] = { ...seatB.position };
          }
          if (studentIdB !== undefined) {
            state.result.student_positions[studentIdB] = { ...seatA.position };
          }
        }),

      // Undo / Redo
      history: [],
      historyFuture: [],

      undo: () =>
        set((state) => {
          if (state.history.length === 0 || !state.result) return;
          const previousResult = state.history[state.history.length - 1];
          const currentSnapshot = structuredClone(current(state.result)) as OptimizationResult;
          state.historyFuture = [currentSnapshot, ...state.historyFuture].slice(0, 20);
          state.history = state.history.slice(0, -1);
          state.result = previousResult;
        }),

      redo: () =>
        set((state) => {
          if (state.historyFuture.length === 0 || !state.result) return;
          const nextResult = state.historyFuture[0];
          const currentSnapshot = structuredClone(current(state.result)) as OptimizationResult;
          state.history = [...state.history, currentSnapshot].slice(-20);
          state.historyFuture = state.historyFuture.slice(1);
          state.result = nextResult;
        }),

      // UI Language
      // Default to Hebrew per product brief — most teachers using
      // SeatAI in the field are Hebrew-speaking. Users can switch
      // immediately from the language picker in the header.
      uiLanguage: 'he',
      setUiLanguage: (lang) =>
        set((state) => { state.uiLanguage = lang; }),

      // UI scale
      uiScale: 'md',
      setUiScale: (scale) =>
        set((state) => { state.uiScale = scale; }),

      theme: 'system',
      setTheme: (theme) =>
        set((state) => { state.theme = theme; }),

      welcomeTipsDismissed: false,
      setWelcomeTipsDismissed: (v) =>
        set((state) => { state.welcomeTipsDismissed = v; }),

      aiSettings: { enabled: false, apiKey: '', model: 'claude-haiku-4-5-20251001' },
      setAiSettings: (s) =>
        set((state) => {
          // Defense in depth: trim whitespace even if the input already trimmed
          // on type — catches paste-then-edit and programmatic callers.
          state.aiSettings = { ...s, apiKey: s.apiKey.trim() };
        }),
      forgetApiKey: () =>
        set((state) => {
          state.aiSettings = { ...state.aiSettings, apiKey: '' };
        }),

      // Collapsed results stack
      resultsCollapsed: false,
      setResultsCollapsed: (v) =>
        set((state) => { state.resultsCollapsed = v; }),

      setShowMovementDiff: (v) =>
        set((state) => { state.showMovementDiff = v; }),

      // Projects
      projects: [],
      currentProjectId: null,

      saveProject: (name) =>
        set((state) => {
          const now = new Date().toISOString();
          const existing = state.projects.find((p: ClassProject) => p.id === state.currentProjectId);
          // Build the persistable snapshot once. Uses structuredClone (faster
          // than JSON round-trip) for nested arrays/objects. `layoutDef` is
          // included so circle / cluster / U-shape projects survive reload.
          const snapshot = {
            students: structuredClone(current(state.students)),
            rows: state.rows,
            cols: state.cols,
            layoutDef: structuredClone(current(state.layoutDef)),
            weights: { ...state.weights },
            config: { ...state.config },
            constraints: structuredClone(current(state.constraints)),
            result: state.result ? structuredClone(current(state.result)) : null,
            rotationPlan: state.rotationPlan
              ? structuredClone(current(state.rotationPlan))
              : null,
            savedArrangements: structuredClone(current(state.savedArrangements)),
          };
          if (existing) {
            Object.assign(existing, snapshot, { name, updatedAt: now });
          } else {
            const id = `proj_${Date.now()}`;
            state.projects.push({
              id,
              name,
              createdAt: now,
              updatedAt: now,
              ...snapshot,
            });
            state.currentProjectId = id;
          }
        }),

      loadProject: (id) =>
        set((state) => {
          const p = state.projects.find((proj: ClassProject) => proj.id === id);
          if (!p) return;
          state.currentProjectId = id;
          state.students = p.students;
          state.rows = p.rows;
          state.cols = p.cols;
          // Pre-multi-layout projects have no layoutDef — fall back to a
          // 'rows' layout reconstructed from rows/cols so they still load.
          state.layoutDef = p.layoutDef ?? { type: 'rows', rows: p.rows, cols: p.cols };
          state.weights = p.weights;
          state.config = p.config;
          state.constraints = p.constraints;
          state.result = p.result;
          state.rotationPlan = p.rotationPlan ?? null;
          state.activeRotationPeriodId = null;
          state.savedArrangements = p.savedArrangements ?? [];
          state.activeArrangementId = null;
          state.history = [];
          state.historyFuture = [];
        }),

      deleteProject: (id) =>
        set((state) => {
          state.projects = state.projects.filter((p: ClassProject) => p.id !== id);
          if (state.currentProjectId === id) state.currentProjectId = null;
        }),

      renameProject: (id, name) =>
        set((state) => {
          const p = state.projects.find((proj: ClassProject) => proj.id === id);
          if (p) {
            p.name = name;
            p.updatedAt = new Date().toISOString();
          }
        }),

      restoreFromBackup: (data) =>
        set((state) => {
          state.students = data.students;
          state.rows = data.rows;
          state.cols = data.cols;
          state.layoutDef = data.layoutDef;
          state.weights = data.weights;
          state.config = data.config;
          state.constraints = data.constraints;
          if (typeof data.avoidRecentNeighbors === 'boolean') {
            state.avoidRecentNeighbors = data.avoidRecentNeighbors;
          }
          state.projects = data.projects;
          state.currentProjectId = data.currentProjectId;
          state.result = data.result ?? null;
          state.resultHistory = data.resultHistory ?? [];
          state.rotationPlan = data.rotationPlan ?? null;
          state.activeRotationPeriodId = null;
          state.savedArrangements = data.savedArrangements ?? [];
          state.activeArrangementId = null;
          if (data.uiLanguage) state.uiLanguage = data.uiLanguage;
          if (data.uiScale) state.uiScale = data.uiScale;
          if (data.theme) state.theme = data.theme;
          // AI settings: copy enabled/model if the backup has them, but
          // preserve the in-browser API key. Backups never carry secrets.
          if (data.aiEnabled !== undefined || data.aiModel) {
            state.aiSettings = {
              enabled: data.aiEnabled ?? state.aiSettings.enabled,
              model: data.aiModel ?? state.aiSettings.model,
              apiKey: state.aiSettings.apiKey,
            };
          }
          // Reset transient UI so the restored data renders cleanly.
          state.history = [];
          state.historyFuture = [];
          state.lockedSeats = [];
          state.selectedSeatKey = null;
          state.previousPositions = null;
          state.detailsTargetStudentId = null;
        }),
    })),
    {
      name: 'seatai-storage',
      storage: createJSONStorage(() => dexieStorage),
      partialize: (state) => ({
        students: state.students,
        rows: state.rows,
        cols: state.cols,
        layoutDef: state.layoutDef,
        weights: state.weights,
        config: state.config,
        constraints: state.constraints,
        avoidRecentNeighbors: state.avoidRecentNeighbors,
        lockedSeats: state.lockedSeats,
        heatMapMode: state.heatMapMode,
        zoomLevel: state.zoomLevel,
        viewMode: state.viewMode,
        projects: state.projects,
        currentProjectId: state.currentProjectId,
        uiLanguage: state.uiLanguage,
        uiScale: state.uiScale,
        theme: state.theme,
        welcomeTipsDismissed: state.welcomeTipsDismissed,
        aiSettings: state.aiSettings,
        resultHistory: state.resultHistory,
        resultsCollapsed: state.resultsCollapsed,
        rotationPlan: state.rotationPlan,
        savedArrangements: state.savedArrangements,
        questionnaire: state.questionnaire,
      }),
    }
  )
);
